### ISSUE TITLE
How to install service in Linux machine

### ISSUE THREAD

**Issue by arvindrajachourasiya** [dejanstojanovic/dotnetcore-windows-linux-service#2]
I am working on creating Linux service using .Net Core. Using `.UseSystemd() ` in `CreateHostBuilder` method I have generated `dll `file.
This file I have copied in Virtual Linux machine. In vm I have installed .Net Core. I copied dll file in Desktop/project folder.

On terminal when I am running `dotnet build` and` dotnet run` getting output 

`Couldn't find a project to run. Ensure a project exists in /home/linux/Desktop/project, or pass the path to the project using --project.`

Are these correct steps I am following? How can I install service in Linux machine?

Thank you.

**Comment by dejanstojanovic** [comment]
I actually built my project on my development machine (Windows) and then just copied binaries to the Linux server where it is supposed to run and finally I used Systemd to register daemon

**Comment by arvindrajachourasiya** [comment]
Thank you. I have installed my service. But getting one error
`dotnet[3634]: The user's home directory could not be determined. Set the 'DOTNET_CLI_HOME' environment variable to spec`

Do you have idea?

**Comment by dejanstojanovic** [comment]
I did not have this issue, but I think it is self explanatory. Systemctl cannot find dotnet to run the dll. Just set the environment variable

**Comment by arvindrajachourasiya** [comment]
Thank you. Where do I need to set variable in windows machine OS or in linux machine OS or in .Net core project(VS2019) ?

**Comment by dejanstojanovic** [comment]
You need to set it on your environment where the application is running (Linux or Windows).
I am not sure why this is happening to you because I believe this should be already in place once you install dotnet. 
Anyway here are some ways to do this on https://dejanstojanovic.net/aspnet/2018/july/different-ways-to-set-environment-for-net-core-application/

**Comment by arvindrajachourasiya** [comment]
@dejanstojanovic - Thank you for your time . That issue has been fixed. https://stackoverflow.com/questions/62039353/how-to-add-environment-variable-to-net-systemd-service
